name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3.2.0
        with:
          github_user_name: mamarezak22
          svg_out_path: dist/github-contribution-grid-snake.svg
